# This is an example of settings that can be used as a starting point for extractting 2D features from MR data 
# This is only intended as a starting point and is not likely to be the optimal settings for your dataset.
# Some points in determining better values are added as comments where appropriate

# When adapting and using these settings for an analysis, be sure to add the PyRadiomics version used to allow you to
# easily recreate your extraction at a later timepoint:

# #############################  Extracted using PyRadiomics version: <version>  ######################################

imageType:
  Original: {}
  LoG:
    sigma: [2.0, 3.0, 4.0, 5.0]
  Wavelet: {}

featureClass:
  shape2D:
  firstorder:
  glcm:
    - 'Autocorrelation'
    - 'JointAverage'
    - 'ClusterProminence'
    - 'ClusterShade'
    - 'ClusterTendency'
    - 'Contrast'
    - 'Correlation'
    - 'DifferenceAverage'
    - 'DifferenceEntropy'
    - 'DifferenceVariance'
    - 'JointEnergy'
    - 'JointEntropy'
    - 'Imc1'
    - 'Imc2'
    - 'Idm'
    - 'Idmn'
    - 'Id'
    - 'Idn'
    - 'InverseVariance'
    - 'MaximumProbability'
    - 'SumEntropy'
    - 'SumSquares'
  glrlm:
  glszm:
  gldm:
  ngtdm:

setting:
  # Normalization:
  normalize: true
  normalizeScale: 100
  
  # Resampling:
  # first dimensions always correspond to in-plane resolution.
  # Z-plane resolution should not be modified to avoid mask errors (> than 1 slice after resampling)
  interpolator: 'sitkBSpline'
  resampledPixelSpacing: [2, 2, 0]
  padDistance: 10
  preCrop: true


  # 2D settings
  # force2Ddimension setting is relative to the acquisition plane.
  # For example, the axial plane (0) corresponds to the acquisition plane (axial, sagittal or coronal) of the MRI volume.
  # Therefore, in most cases this setting should not be modified.
  force2D: true
  force2Ddimension: 0
  
  # Image discretization:
  # This parameter should be estimated by analyzing the dataset firstorder range and chosen to be as close as possible to the 30-130 range. 
  binWidth: 5

  # first order specific settings:
  voxelArrayShift: 300

  # Misc:
  label: 1
